### PR TITLE
[Dead PR now I believe] Exercises ported from other language examples.

### PR DESCRIPTION
**Pull request by rpottsoh**
Not really sure what files really needed to be included in this PR.  uHelloWorld.pas contains the example CUT and uTestHelloWorld.pas contains the test framework.

### CODE REVIEW

**Comment by kytrinyx** [comment]
There are a couple of things this needs:

1. The example solution needs to be named with example in the name (case insensitive), otherwise it will be served to people when they fetch the exercise.
2. The config.json needs to have "hello-world" in the exercises list.

The exercises list format should look like the description in Step 1 of the launch checklist: https://github.com/exercism/xpascal/issues/1

**Comment by rpottsoh** [comment]
Should I assume everything not having example in its name will be served up?  Does this also apply to folder names?

**Comment by rpottsoh** [comment]
I am wondering if this is really going to be a Pascal track but really a Delphi track?  I am implementing the exercises using Delphi XE5.  Yes, it is Pascal, but it has Embarcadero's spin on the language.  Students would be able to perform the exercises using Delphi and maybe could muddle through with Lazarus; any other form of Pascal compiler will likely not work.

Just thinking outloud.

**Comment by rpottsoh** [comment]
I'm seeing some error messages pertaining to Travis.  Should I refrain from adding more exercises for the time being?

**Comment by kytrinyx** [comment]
> Should I assume everything not having example in its name will be served up? Does this also apply to folder names?

Yes, as long as it's in the path (under `exercises/`) it will be ignored when people fetch it.

> I am wondering if this is really going to be a Pascal track but really a Delphi track?

That's a good question. We might want to rename this to Pascal Delphi or something like that. It is much easier to change it now than to do it later.

> I'm seeing some error messages pertaining to Travis.

The error message is this:

```
Evaluating .
-> config.json is invalid. Try jsonlint.com
```

I have a script locally that validates json. It relies on the `jq` library. But jsonlint also works.

```
#!/usr/bin/env bash

STATUS=0
cat $1 | jq . > /dev/null 2>&1
if [ $? != 0 ]; then
	echo "Invalid json: $1"
	STATUS=1
fi
exit $STATUS
```

Ideally I would like to see each individual exercise in a separate commit, with no extra merge commits "fix X" commits. To make this easier I would recommend making separate pull requests for each exercise on different branches.

```
$ git branch -m backup
$ git fetch origin master
$ git checkout -t origin/master
$ git checkout -b hello-world # or beer-song or whatever
```

Then you can `git log backup` and find the SHA1 hashes of the commits for hello-world (or whatever), and then

```
$ git cherry-pick THE_SHA1_HASH
```

Finally, when you have cherrypicked all the relevant hashes, you can squash and push up to a branch to create a separate PR.

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by rpottsoh** [comment]
Katrina,

 

                I’ll try to follow your directions in regards to having separate commits for each exercise.  I only use GitHub sparingly, just for my personal stuff and have not delved into using actual git calls to make things happen, but instead relying on the GitHub Windows interface and the web interface.

 

                I started out with a fork of the new Pascal track that you made available to me and cloned a copy of the fork to my computer.  I didn’t start off creating branches but eventually started creating branches for each new exercise I started.  I would have multiple branches going at once, which wasn’t a real problem until I started making commits to .gitignore while in each of the different branches; things seemed to get out of sync real quick.  Once an exercise was completed I would create a PR back to my master (this was problematic early on when I had multiple branches going at once with .gitignore out of sync).  In the web interface I got into the habit of doing a squash merge and then deleting the branch…  Every time I did this a new commit was appended to the PR that I had made, after completing hello-world, to exercism/xpascal.  As I progressed I decided to only create one branch at a time to avoid the issue I was having with .gitignore getting out of sync.  Maybe you have noticed this as you scroll down the PR. 

 

<90 minutes later>

 

                I was not having much success following your git steps for creating individual PRs based on the commits I have made by cherry-picking SHAs.  I essentially started over.  I created branches for each exercise, made a commit for each exercise, and finally a PR for each commit.  I think this is essentially what you were trying to achieve.  All this should make the initial PR obsolete.

 

Thanks,

 

Ryan

**Comment by kytrinyx** [comment]
@rpottsoh Yes, this is exactly what I was trying to achieve. I'll try to get this all reviewed this weekend.

**Comment by rpottsoh** [comment]
Thanks @kytrinyx.  I may work on another exercise this evening.

**Pull request closed without merging**
