### PR TITLE
Added exercise call-outs to config.json

### PR DESCRIPTION
**Pull request by rpottsoh**

### CODE REVIEW

**Comment by rpottsoh** [comment]
JSON file is passing travis.  Error is simply due to the fact that the other PRs for the exercises haven't been merged so their folders do not exist for Travis to find.

**Comment by rpottsoh** [comment]
As near as I can tell this PR is ready to be merged.  I do not have adequate persmissions to merge PRs here.

**Comment by rpottsoh** [comment]
@exercism/pascal should we have access to merging PRs here @ xpascal?

**Comment by kotp** [comment]
Yes, yes we should.  @jtigger may be able to help out here.

**Pull request merged**
